id: P922AC347
initial_creation_type: input
source_metadata:
  title: Tantrāloka
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Jun Takashima
  contribution to GRETIL: Jun Takashima
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:06:00.337500'
last_modified_at: '2022-03-09T15:06:00.337514'
